[project]
name = "tp-simulation-ap-mines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcade>=3.3.3",
    "numpy>=2.4.1",
]
